nameOfStudent=str(input("Enter the name of student:"))
ageOfStudent=int(input("Enter the age of student:"))
rollNoStudent=int(input("Enter the Roll No. of student:"))
genderStudent=str(input("Enter the gender of student:"))
averageMarksOfStudent=float(input("Enter the average marks of student:"))
print(nameOfStudent,ageOfStudent,rollNoStudent,genderStudent,averageMarksOfStudent)
print("Type of variable Name is=",type(nameOfStudent))
print("Type of variable Age is=",type(ageOfStudent))
print("Type of variable Roll No. is=",type(rollNoStudent))
print("Type of variable Gender is=",type(genderStudent))
print("Type of variable Average Marks is=",type(averageMarksOfStudent))
